### ISSUE TITLE
Issue with Windows PowerShell 

### ISSUE THREAD

**Issue by Okilele56** [wong2/pick#75]
Hi 
The multiselect mode do not work on windows powershell since the version 1.6.0 (1.4.0 is working). 

![image](https://user-images.githubusercontent.com/79262634/187929026-fa13f32e-fd9a-408c-8666-b89b53a4710f.png)

**Comment by wong2** [comment]
Got it

**Comment by wong2** [comment]
Hi, can you help me get the output of `sys.stdout.encoding` in PowerShell?

**Comment by wong2** [comment]
What version of Windows are you using?

**Comment by Okilele56** [comment]
I am using Windows 10 professionnel

**Comment by guiserle** [comment]
Funnily enough, I have the same problem on windows cmd but it works fine on powershell. 
Would there be any chance to revert back to background color instead of character on demand? (maybe with a keyword argument)

**Comment by wong2** [comment]
I prefer the character method, but we can fall back to simple chars like `()` and `(*)` on terminals that don't support unicode. I haven't found out how to do the checking yet.

**Comment by guiserle** [comment]
After some research, I think this is not related to the terminal itself but to the font used by the terminal.
I managed to make it work on CMD by setting the font to Cascadia Mono, which is the default for Windows Terminal, where I was using powershell.

Also using CMD on windows terminal didn't gave me the error, since it was already using Cascadia Mono font.

Therefore I am not sure if it would make sense to apply the fallback automatically. Either just noticing this behavior on README.md file or adding an extra argument to allow for manual fallback (or both options) would be fine on my opinion

**Comment by wong2** [comment]
Thanks for your research! I'll try to find some way for automatic fallback

**Comment by wong2** [comment]
I've decided to go the simple path: change those symbols to simpler ones that should work universally. Please upgrade to v2.0.1
